env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
overrides:
  files: ['index.js']
  env:
    node: false
    shared-node-browser: true
  parserOptions:
    sourceType: script
  globals:
    require: false
    module: false
    exports: true
    window: false
    global: false
    URL: false
